import './globals.css';
import Head from 'next/head';

export const metadata = {
  title: 'Template',
  description: 'Welcome to Beqa Tvildiani\'s personal Template',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Basic Next.js Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-white dark:bg-black text-gray-900 dark:text-gray-100">
        {/* Main content */}
        <main className="bg-gray-900 min-h-[85vh]">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-800 p-4 absolute b-0 w-full">
          <div className="container mx-auto text-center text-white">
            <p>&copy; Template | Design by <a href="https://github.com/Isabela1082" className="text-blue-400">nino</a></p>
          </div>
        </footer>
      </body>
    </html>
  );
}